import type { PageSection, SfPreset } from './types'

const baseSections: PageSection[] = [
  { id: 'header', type: 'header' },
  { id: 'status', type: 'status' },
  { id: 'hero', type: 'hero' },
  { id: 'search', type: 'search' },
  { id: 'categories', type: 'categories' },
  { id: 'products', type: 'products' },
  { id: 'promo', type: 'promo' },
  { id: 'featured', type: 'featured' },
  { id: 'reviews', type: 'reviews' },
  { id: 'story', type: 'story' },
  { id: 'info', type: 'info' },
  { id: 'footer', type: 'footer' },
  { id: 'cartbar', type: 'cartbar' },
]

export const PRESETS: SfPreset[] = [
  {
    theme: {
      id: 'editorial',
      name: 'Editorial Brutalista',
      description: 'Padrão Doispalitos. Off-white, borda fina, amarelo manteiga.',
      designStyle: 'brutalista / editorial',
      dark: false,
      colors: {
        bg: '#F8F7F4',
        surface: '#FFFFFF',
        surface2: '#F0EFEA',
        text: '#141416',
        muted: '#737377',
        primary: '#F5DC55',
        primaryText: '#141416',
        accent: '#141416',
        border: '#E5E4DC',
      },
      fonts: { head: '"Plus Jakarta Sans", sans-serif', body: '"Plus Jakarta Sans", sans-serif' },
      radius: 14,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'comfortable',
      texture: 'none',
      cardVariant: 'photo-left',
      headerVariant: 'minimal',
      heroVariant: 'split',
      categoryVariant: 'pills',
      buttonVariant: 'rounded',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'dark-luxo',
      name: 'Dark Luxo',
      description: 'Hamburgueria premium. Preto zinco, âmbar, tipografia forte.',
      designStyle: 'dark luxe / premium',
      dark: true,
      colors: {
        bg: '#0F1012',
        surface: '#16171B',
        surface2: '#1E2026',
        text: '#F4F2EA',
        muted: '#9B9CA6',
        primary: '#E8B93E',
        primaryText: '#141416',
        accent: '#E8B93E',
        border: '#2A2D36',
      },
      fonts: { head: '"Space Grotesk", sans-serif', body: '"Inter", sans-serif' },
      radius: 16,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'comfortable',
      texture: 'dots',
      cardVariant: 'photo-top',
      headerVariant: 'centered',
      heroVariant: 'cover',
      categoryVariant: 'pills',
      buttonVariant: 'pill',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'cozy',
      name: 'Cozy Artesanal',
      description: 'Marmitaria / padaria. Creme, marrom, serifada acolhedora.',
      designStyle: 'cozy / handmade',
      dark: false,
      colors: {
        bg: '#FFF8EC',
        surface: '#FFFFFF',
        surface2: '#F7EBD3',
        text: '#3E2E20',
        muted: '#9A8271',
        primary: '#C96F2B',
        primaryText: '#FFFFFF',
        accent: '#5C7C4C',
        border: '#EBDCC3',
      },
      fonts: { head: '"DM Serif Display", serif', body: '"Inter", sans-serif' },
      radius: 22,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'airy',
      texture: 'paper',
      cardVariant: 'photo-top',
      headerVariant: 'centered',
      heroVariant: 'split',
      categoryVariant: 'photos',
      buttonVariant: 'pill',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'glass-noite',
      name: 'Glass Noite',
      description: 'Açaí / drinks. Vidro escuro, roxo+ciano, glow.',
      designStyle: 'glassmorphism',
      dark: true,
      colors: {
        bg: '#0B0714',
        surface: 'rgba(255,255,255,0.07)',
        surface2: 'rgba(255,255,255,0.12)',
        text: '#F2EDFF',
        muted: '#A79FC4',
        primary: '#A78BFA',
        primaryText: '#0B0714',
        accent: '#22D3EE',
        border: 'rgba(255,255,255,0.14)',
      },
      fonts: { head: '"Space Grotesk", sans-serif', body: '"Inter", sans-serif' },
      radius: 24,
      borderWidth: 1,
      shadow: 'glow',
      spacing: 'comfortable',
      texture: 'grid',
      cardVariant: 'glass',
      headerVariant: 'split',
      heroVariant: 'glass-promo',
      categoryVariant: 'pills',
      buttonVariant: 'pill',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'japandi',
      name: 'Minimal Japandi',
      description: 'Saudável / oriental. Muito respiro, pedra, sem sombra.',
      designStyle: 'minimalista',
      dark: false,
      colors: {
        bg: '#FFFFFF',
        surface: '#FFFFFF',
        surface2: '#F4F4F2',
        text: '#1C1C1A',
        muted: '#8E8E89',
        primary: '#1C1C1A',
        primaryText: '#FFFFFF',
        accent: '#7A8B6F',
        border: '#E9E9E6',
      },
      fonts: { head: '"Inter", sans-serif', body: '"Inter", sans-serif' },
      radius: 10,
      borderWidth: 1,
      shadow: 'none',
      spacing: 'airy',
      texture: 'none',
      cardVariant: 'editorial',
      headerVariant: 'minimal',
      heroVariant: 'typo',
      categoryVariant: 'underline',
      buttonVariant: 'square',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'pop',
      name: 'Pop Doceria',
      description: 'Doceria / festas. Rosa+amarelo, cards fofos, borda grossa.',
      designStyle: 'playful / pop',
      dark: false,
      colors: {
        bg: '#FFF6FB',
        surface: '#FFFFFF',
        surface2: '#FFE9F4',
        text: '#3A2340',
        muted: '#A584AE',
        primary: '#FF5FA2',
        primaryText: '#FFFFFF',
        accent: '#FFC531',
        border: '#3A2340',
      },
      fonts: { head: '"Fredoka", sans-serif', body: '"Plus Jakarta Sans", sans-serif' },
      radius: 20,
      borderWidth: 2,
      shadow: 'hard',
      spacing: 'comfortable',
      texture: 'dots',
      cardVariant: 'photo-top',
      headerVariant: 'cover',
      heroVariant: 'minimal',
      categoryVariant: 'photos',
      buttonVariant: 'hard',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'trattoria',
      name: 'Trattoria Italiana',
      description: 'Cultura italiana clássica. Creme, verde manjericão, vermelho tomate, serifada.',
      designStyle: 'cultural / italiano clássico',
      dark: false,
      colors: {
        bg: '#FAF5E9',
        surface: '#FFFFFF',
        surface2: '#F1E6CE',
        text: '#2B2118',
        muted: '#8A7A64',
        primary: '#B33A2B',
        primaryText: '#FFFFFF',
        accent: '#2F6B3A',
        border: '#E3D5B8',
      },
      fonts: { head: '"Playfair Display", serif', body: '"Inter", sans-serif' },
      radius: 12,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'comfortable',
      texture: 'paper',
      cardVariant: 'photo-left',
      headerVariant: 'centered',
      heroVariant: 'split',
      categoryVariant: 'underline',
      buttonVariant: 'rounded',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'fresh',
      name: 'Fresh Saudável',
      description: 'Plant-forward / sustentável. Branco arrejado, verde fresco, tipografia leve.',
      designStyle: 'fresh / saudável',
      dark: false,
      colors: {
        bg: '#F7FAF5',
        surface: '#FFFFFF',
        surface2: '#E9F3E6',
        text: '#1E2B21',
        muted: '#7A8F7E',
        primary: '#3E9B4F',
        primaryText: '#FFFFFF',
        accent: '#D8E93C',
        border: '#DDE8DB',
      },
      fonts: { head: '"Plus Jakarta Sans", sans-serif', body: '"Inter", sans-serif' },
      radius: 18,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'airy',
      texture: 'none',
      cardVariant: 'editorial',
      headerVariant: 'minimal',
      heroVariant: 'typo',
      categoryVariant: 'pills',
      buttonVariant: 'pill',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'retro-diner',
      name: 'Retrô Diner',
      description: 'Nostalgia americana. Creme, vermelho cereja, azul pastel, tipografia gordinha.',
      designStyle: 'retrô / nostalgia comfort',
      dark: false,
      colors: {
        bg: '#FFF9F0',
        surface: '#FFFFFF',
        surface2: '#FDEBD3',
        text: '#2E2A26',
        muted: '#A08E7E',
        primary: '#E23E3E',
        primaryText: '#FFFFFF',
        accent: '#2D7DD2',
        border: '#2E2A26',
      },
      fonts: { head: '"Fredoka", sans-serif', body: '"Plus Jakarta Sans", sans-serif' },
      radius: 16,
      borderWidth: 2,
      shadow: 'hard',
      spacing: 'comfortable',
      texture: 'dots',
      cardVariant: 'photo-top',
      headerVariant: 'split',
      heroVariant: 'cover',
      categoryVariant: 'photos',
      buttonVariant: 'hard',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'cafe-brunch',
      name: 'Café Aconchego',
      description: 'Cafeteria / brunch. Bege quente, marrom café, serifada convidativa.',
      designStyle: 'cozy / café & brunch',
      dark: false,
      colors: {
        bg: '#F7F3EC',
        surface: '#FFFFFF',
        surface2: '#EDE3D2',
        text: '#3B2F2A',
        muted: '#A08B78',
        primary: '#8A5A33',
        primaryText: '#FFFFFF',
        accent: '#C9A227',
        border: '#E2D5BE',
      },
      fonts: { head: '"DM Serif Display", serif', body: '"Inter", sans-serif' },
      radius: 18,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'airy',
      texture: 'paper',
      cardVariant: 'photo-left',
      headerVariant: 'centered',
      heroVariant: 'split',
      categoryVariant: 'pills',
      buttonVariant: 'pill',
      motion: 'subtle',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'oriental',
      name: 'Oriental Express',
      description: 'Japonesa / chinesa. Preto tinta, dourado e vermelho lacre.',
      designStyle: 'cultural / oriental',
      dark: true,
      colors: {
        bg: '#141011',
        surface: '#211917',
        surface2: '#2C2220',
        text: '#F7F1E6',
        muted: '#A89A8C',
        primary: '#D9A441',
        primaryText: '#141011',
        accent: '#C62F2F',
        border: '#3A2E2A',
      },
      fonts: { head: '"Space Grotesk", sans-serif', body: '"Inter", sans-serif' },
      radius: 12,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'comfortable',
      texture: 'dots',
      cardVariant: 'photo-top',
      headerVariant: 'split',
      heroVariant: 'cover',
      categoryVariant: 'pills',
      buttonVariant: 'rounded',
      motion: 'subtle',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'boteco',
      name: 'Boteco Raiz',
      description: 'Boteco / petiscos. Amarelo ouro, verde garrafa, tipografia gordinha.',
      designStyle: 'brasileiro / boteco',
      dark: false,
      colors: {
        bg: '#FFF8E7',
        surface: '#FFFFFF',
        surface2: '#FBEFD4',
        text: '#23201A',
        muted: '#97876F',
        primary: '#F2B705',
        primaryText: '#23201A',
        accent: '#1E7A46',
        border: '#23201A',
      },
      fonts: { head: '"Fredoka", sans-serif', body: '"Plus Jakarta Sans", sans-serif' },
      radius: 14,
      borderWidth: 2,
      shadow: 'hard',
      spacing: 'comfortable',
      texture: 'dots',
      cardVariant: 'photo-left',
      headerVariant: 'cover',
      heroVariant: 'minimal',
      categoryVariant: 'photos',
      buttonVariant: 'hard',
      motion: 'playful',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'padaria',
      name: 'Pão Quente Padaria',
      description: 'Padaria de bairro. Trigo, crosta dourada, clima de manhã.',
      designStyle: 'cozy / padaria',
      dark: false,
      colors: {
        bg: '#FFF9F1',
        surface: '#FFFFFF',
        surface2: '#F6EAD8',
        text: '#4A3428',
        muted: '#A68B74',
        primary: '#D99A2B',
        primaryText: '#3A2A1A',
        accent: '#7A9E43',
        border: '#E8D9C2',
      },
      fonts: { head: '"Playfair Display", serif', body: '"Inter", sans-serif' },
      radius: 16,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'airy',
      texture: 'paper',
      cardVariant: 'photo-left',
      headerVariant: 'centered',
      heroVariant: 'split',
      categoryVariant: 'pills',
      buttonVariant: 'pill',
      motion: 'subtle',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'brasa',
      name: 'Fogo & Brasa',
      description: 'Churrascaria / fogo. Preto carvão, laranja brasa, dourado.',
      designStyle: 'dark / churrasco & fogo',
      dark: true,
      colors: {
        bg: '#120D0B',
        surface: '#1E1512',
        surface2: '#2A1E19',
        text: '#F5EBDD',
        muted: '#A89880',
        primary: '#E4572E',
        primaryText: '#120D0B',
        accent: '#F2A007',
        border: '#3A2C24',
      },
      fonts: { head: '"Space Grotesk", sans-serif', body: '"Inter", sans-serif' },
      radius: 12,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'comfortable',
      texture: 'dots',
      cardVariant: 'photo-top',
      headerVariant: 'split',
      heroVariant: 'cover',
      categoryVariant: 'pills',
      buttonVariant: 'rounded',
      motion: 'subtle',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'acai',
      name: 'Açaí Tropical',
      description: 'Açaíteria / praiana. Roxo açaí, verde limão, vidro noturno.',
      designStyle: 'tropical / açaí',
      dark: true,
      colors: {
        bg: '#1E0B2E',
        surface: '#2E1445',
        surface2: '#3B1C58',
        text: '#F6EFFC',
        muted: '#B9A4D6',
        primary: '#A855F7',
        primaryText: '#FFFFFF',
        accent: '#4ADE80',
        border: '#4A2E6B',
      },
      fonts: { head: '"Fredoka", sans-serif', body: '"Plus Jakarta Sans", sans-serif' },
      radius: 22,
      borderWidth: 1,
      shadow: 'glow',
      spacing: 'comfortable',
      texture: 'grid',
      cardVariant: 'glass',
      headerVariant: 'centered',
      heroVariant: 'glass-promo',
      categoryVariant: 'pills',
      buttonVariant: 'pill',
      motion: 'playful',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'smash',
      name: 'Smash Burger',
      description: 'Hamburgueria smash. Preto, amarelo mostarda e vermelho ketchup.',
      designStyle: 'brutalista / burger',
      dark: true,
      colors: {
        bg: '#131313',
        surface: '#1E1E1E',
        surface2: '#2A2A2A',
        text: '#FAF6EC',
        muted: '#A39E93',
        primary: '#FFC700',
        primaryText: '#131313',
        accent: '#E23E22',
        border: '#383838',
      },
      fonts: { head: '"Space Grotesk", sans-serif', body: '"Inter", sans-serif' },
      radius: 14,
      borderWidth: 2,
      shadow: 'hard',
      spacing: 'comfortable',
      texture: 'grid',
      cardVariant: 'photo-left',
      headerVariant: 'split',
      heroVariant: 'cover',
      categoryVariant: 'pills',
      buttonVariant: 'hard',
      motion: 'playful',
    },
    sections: baseSections,
  },
  {
    theme: {
      id: 'gelato',
      name: 'Gelato Artigianale',
      description: 'Sorveteria artesanal. Creme, menta e rosa pastel delicados.',
      designStyle: 'pastel / sorveteria',
      dark: false,
      colors: {
        bg: '#FFF9F5',
        surface: '#FFFFFF',
        surface2: '#FDEFE3',
        text: '#4A3B36',
        muted: '#B39D94',
        primary: '#7FD1C0',
        primaryText: '#23403A',
        accent: '#F5A8C0',
        border: '#F0E0D4',
      },
      fonts: { head: '"Fredoka", sans-serif', body: '"Plus Jakarta Sans", sans-serif' },
      radius: 24,
      borderWidth: 1,
      shadow: 'soft',
      spacing: 'airy',
      texture: 'dots',
      cardVariant: 'photo-top',
      headerVariant: 'centered',
      heroVariant: 'split',
      categoryVariant: 'photos',
      buttonVariant: 'pill',
      motion: 'playful',
    },
    sections: baseSections,
  },
]
